from setuptools import setup, find_packages

setup(
    name="fit-vton",
    version="0.1.0",
    description="FIT-VTON: Measurement-Conditioned Virtual Try-On via FitAdapter",
    author="NatalieCarlebach1",
    author_email="nataliecarlebach@gmail.com",
    url="https://github.com/NatalieCarlebach1/fit-vton",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.10",
    install_requires=[
        "torch>=2.1.0",
        "torchvision>=0.16.0",
        "diffusers>=0.27.0",
        "transformers>=4.38.0",
        "accelerate>=0.27.0",
        "huggingface_hub>=0.21.0",
        "peft>=0.9.0",
        "safetensors>=0.4.0",
        "einops>=0.7.0",
        "omegaconf>=2.3.0",
        "wandb>=0.16.0",
        "opencv-python>=4.9.0",
        "pillow>=10.0.0",
        "numpy>=1.26.0",
        "scipy>=1.12.0",
        "scikit-image>=0.22.0",
        "matplotlib>=3.8.0",
        "tqdm>=4.66.0",
        "rich>=13.7.0",
        "gdown>=5.1.0",
        "requests>=2.31.0",
        "pandas>=2.2.0",
        "lpips>=0.1.4",
        "clean-fid>=0.1.35",
    ],
    entry_points={
        "console_scripts": [
            "fit-vton-train=fit_vton.training.trainer:main",
        ],
    },
    classifiers=[
        "Programming Language :: Python :: 3.10",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
)
